In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow.python'

In [3]:
# Dữ liệu ban đầu
data = {
    'Level': [1, 2, 3, 1, 2],
    'Lives': [3, 1, 2, 2, 3],
    'Time': [10, 20, 15, 5, 25],
    'Result': [1, 0, 0, 1, 1]
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

Level  Lives  Time  Result
0      1      3    10       1
1      2      1    20       0
2      3      2    15       0
3      1      2     5       1
4      2      3    25       1

In [16]:
x = df[['Level','Lives','Time']].values
y = df[['Result']].values
print(x,y)

[[ 1  3 10]
 [ 2  1 20]
 [ 3  2 15]
 [ 1  2  5]
 [ 2  3 25]] [[1]
 [0]
 [0]
 [1]
 [1]]


In [ ]:
#Khởi tạo trọng số và bias
np.random.seed(42)

input_dim = x.shape[1]
hidden_dim = 2
output_dim = 1